### ISSUE TITLE
v1 feature tracking

### ISSUE THREAD

**Issue by jonasteuwen** [NKI-AI/dlup#170]
- [x] strict mypy parsing (#169)
- [ ] 100% test coverage (#168)
- [ ] Do not resample when close to level (#167). Consider that inference might need resampling
- [ ] Refactor TiledWsiDataset, functionality of base class should move in (or add a third class)
- [ ] Remove masking and deprecation warnings 
- [ ] Add more documentation
- [x] Add CITATION.cff (#159)
- [ ] Remove "Any" typing whereever possible
- [ ] Solve any TODOs
- [ ] Figure out any `# type: ignore`
- [ ] Give classes shorter names
