### ISSUE TITLE
v1 tracking and discussion

### ISSUE THREAD

**Issue by jonasteuwen** [NKI-AI/dlup#200]
Proposed changes for v1.0:

- [ ] 100% test coverage
- [x] Removing the dlup tiling utilities (#209)
- [x] Removing the dlup mask computation utilities (#209)
- [ ] Remove multiscale dataset (#211)
- [ ] Up-to-date documentation
- [ ] JOSS paper
- [ ] h5reader + writer backend
- [ ] Add ahcore tiling utility
- [ ] Backends to read pre-tiled images
