### ISSUE TITLE
version 1.0 tracking

### ISSUE THREAD

**Issue by jonasteuwen** [NKI-AI/dlup#227]
- [ ] 100% test coverage
- [ ] Add test for TIFF pyramid
- [ ] Add more elaborate tests for `read_region`
- [ ] Add public datasets -> TiledWsiDataset or SlideImage
- [ ] Add more backends #225
- [ ] Improve documentation (@AjeyPaiK) and submit to JOSS
- [ ] Lazy image
