### ISSUE TITLE
v0.5 tracking

### ISSUE THREAD

**Issue by jonasteuwen** [NKI-AI/dlup#231]
- [x] Colors and z_indices (#228)
- [x] Update GeoJSON parsing (#228)
- [x] Support multiclass masking (#232) (#228)
