### ISSUE TITLE
v0.7 tracking

### ISSUE THREAD

**Issue by jonasteuwen** [NKI-AI/dlup#244]
- [ ] Remove PIL handling
- [ ] Apply ICC profile directly in pyvips backend
- [ ] Increase test coverage
- [ ] Improve sum_mask_2d function
